# 运行 go-task 命令 而不是 task 命令
# go-task build

version: "3"

tasks:
  default:
    cmds:
      - clear
      - task: dev

  dev:
    cmds:
      - go run ./cmd/sshole hub
      # - go run ./cmd/sshole agent
      # - go run ./cmd/sshole entry

  gen:
    cmds:
      - buf generate