# 运行 go-task 命令 而不是 task 命令
# go-task build

version: "3"

tasks:
  clear:
    internal: true
    silent: true
    run: once
    cmds:
      - clear

  default:
    cmds:
      - clear
      - task: dev

  dev:
    cmds:
      - go run ./cmd/sshole hub
      # - go run ./cmd/sshole agent
      # - go run ./cmd/sshole entry

  gen:
    cmds:
      - buf generate

  build:
    deps: [clear]
    sources:
      - ./cmd/**
      - ./internal/**
      - ./pkg/**
      - ./.git/**
      - ./go.mod
      - ./go.sum
      - ./Taskfile.yml
      - ./scripts/script/**
    generates:
      - ./data/sshole/sshole
    cmds:
      - cd ./scripts/script && go run . build

  format:
    deps: [clear]
    cmds:
      - cd ./scripts/script && go run . format

  build-docker:
    deps: [clear, build]
    sources:
      - ./scripts/Dockerfile
      - ./data/sshole/sshole
    cmds:
      - docker build -t 117503445/sshole -f ./scripts/Dockerfile .