# 运行 go-task 命令 而不是 task 命令
# go-task build

version: "3"

tasks:
  clear:
    internal: true
    silent: true
    run: once
    cmds:
      - clear || true

  default:
    cmds:
      - clear
      - task: dev

  dev:
    cmds:
      - task: e2e

  gen:
    sources:
      - pkg/rpc/v1/sshole.proto
      - buf.gen.yaml
      - buf.yaml
    generates:
      - ./pkg/rpc/v1/sshole.pb.go
      - ./pkg/rpc/v1/rpcv1connect/sshole.connect.go
    cmds:
      - buf generate

  build:
    deps: [clear, gen]
    sources:
      - ./cmd/**
      - ./internal/**
      - ./pkg/**
      - ./.git/**
      - ./go.mod
      - ./go.sum
      - ./Taskfile.yml
      - ./scripts/script/**
    generates:
      - ./data/agent/sshole_agent
      - ./data/entry/sshole_entry
      - ./data/hub/sshole_hub
    cmds:
      - cd ./scripts/script && go run . build

  format:
    deps: [clear]
    cmds:
      - cd ./scripts/script && go run . format

  build-docker:
    deps: [clear, build]
    sources:
      - ./scripts/docker/agent.Dockerfile
      - ./data/agent/sshole_agent
      - ./scripts/docker/hub.Dockerfile
      - ./data/hub/sshole_hub
    cmds:
      - docker build -t 117503445/sshole-agent -f ./scripts/docker/agent.Dockerfile .
      - docker build -t 117503445/sshole-hub -f ./scripts/docker/hub.Dockerfile .

  e2e:
    deps: [clear, build-docker]
    cmds:
      - cd ./scripts/script && go run . e-2-e