// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pkg/rpc/v1/sshole.proto

package rpcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApiRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Auth  string                 `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"` // auth to hub
	// Types that are valid to be assigned to Payload:
	//
	//	*ApiRequest_AgentCreate
	//	*ApiRequest_AgentList
	//	*ApiRequest_AgentGet
	//	*ApiRequest_AgentAppendPublicKey
	Payload       isApiRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiRequest) Reset() {
	*x = ApiRequest{}
	mi := &file_pkg_rpc_v1_sshole_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiRequest) ProtoMessage() {}

func (x *ApiRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_sshole_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiRequest.ProtoReflect.Descriptor instead.
func (*ApiRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_sshole_proto_rawDescGZIP(), []int{0}
}

func (x *ApiRequest) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

func (x *ApiRequest) GetPayload() isApiRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ApiRequest) GetAgentCreate() *AgentCreateRequest {
	if x != nil {
		if x, ok := x.Payload.(*ApiRequest_AgentCreate); ok {
			return x.AgentCreate
		}
	}
	return nil
}

func (x *ApiRequest) GetAgentList() *AgentListRequest {
	if x != nil {
		if x, ok := x.Payload.(*ApiRequest_AgentList); ok {
			return x.AgentList
		}
	}
	return nil
}

func (x *ApiRequest) GetAgentGet() *AgentGetRequest {
	if x != nil {
		if x, ok := x.Payload.(*ApiRequest_AgentGet); ok {
			return x.AgentGet
		}
	}
	return nil
}

func (x *ApiRequest) GetAgentAppendPublicKey() *AgentAppendPublicKeyRequest {
	if x != nil {
		if x, ok := x.Payload.(*ApiRequest_AgentAppendPublicKey); ok {
			return x.AgentAppendPublicKey
		}
	}
	return nil
}

type isApiRequest_Payload interface {
	isApiRequest_Payload()
}

type ApiRequest_AgentCreate struct {
	AgentCreate *AgentCreateRequest `protobuf:"bytes,2,opt,name=agent_create,json=agentCreate,proto3,oneof"`
}

type ApiRequest_AgentList struct {
	AgentList *AgentListRequest `protobuf:"bytes,3,opt,name=agent_list,json=agentList,proto3,oneof"`
}

type ApiRequest_AgentGet struct {
	AgentGet *AgentGetRequest `protobuf:"bytes,4,opt,name=agent_get,json=agentGet,proto3,oneof"`
}

type ApiRequest_AgentAppendPublicKey struct {
	AgentAppendPublicKey *AgentAppendPublicKeyRequest `protobuf:"bytes,5,opt,name=agent_append_public_key,json=agentAppendPublicKey,proto3,oneof"`
}

func (*ApiRequest_AgentCreate) isApiRequest_Payload() {}

func (*ApiRequest_AgentList) isApiRequest_Payload() {}

func (*ApiRequest_AgentGet) isApiRequest_Payload() {}

func (*ApiRequest_AgentAppendPublicKey) isApiRequest_Payload() {}

type ApiResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Code    int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// 根据 RPC 类型填充对应 payload
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*ApiResponse_AgentCreate
	//	*ApiResponse_AgentList
	//	*ApiResponse_AgentGet
	//	*ApiResponse_AgentAppendPublicKey
	Payload       isApiResponse_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApiResponse) Reset() {
	*x = ApiResponse{}
	mi := &file_pkg_rpc_v1_sshole_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApiResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApiResponse) ProtoMessage() {}

func (x *ApiResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_sshole_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApiResponse.ProtoReflect.Descriptor instead.
func (*ApiResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_sshole_proto_rawDescGZIP(), []int{1}
}

func (x *ApiResponse) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ApiResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ApiResponse) GetPayload() isApiResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ApiResponse) GetAgentCreate() *AgentCreateResponse {
	if x != nil {
		if x, ok := x.Payload.(*ApiResponse_AgentCreate); ok {
			return x.AgentCreate
		}
	}
	return nil
}

func (x *ApiResponse) GetAgentList() *AgentListResponse {
	if x != nil {
		if x, ok := x.Payload.(*ApiResponse_AgentList); ok {
			return x.AgentList
		}
	}
	return nil
}

func (x *ApiResponse) GetAgentGet() *AgentGetResponse {
	if x != nil {
		if x, ok := x.Payload.(*ApiResponse_AgentGet); ok {
			return x.AgentGet
		}
	}
	return nil
}

func (x *ApiResponse) GetAgentAppendPublicKey() *AgentAppendPublicKeyResponse {
	if x != nil {
		if x, ok := x.Payload.(*ApiResponse_AgentAppendPublicKey); ok {
			return x.AgentAppendPublicKey
		}
	}
	return nil
}

type isApiResponse_Payload interface {
	isApiResponse_Payload()
}

type ApiResponse_AgentCreate struct {
	AgentCreate *AgentCreateResponse `protobuf:"bytes,3,opt,name=agent_create,json=agentCreate,proto3,oneof"`
}

type ApiResponse_AgentList struct {
	AgentList *AgentListResponse `protobuf:"bytes,4,opt,name=agent_list,json=agentList,proto3,oneof"`
}

type ApiResponse_AgentGet struct {
	AgentGet *AgentGetResponse `protobuf:"bytes,5,opt,name=agent_get,json=agentGet,proto3,oneof"`
}

type ApiResponse_AgentAppendPublicKey struct {
	AgentAppendPublicKey *AgentAppendPublicKeyResponse `protobuf:"bytes,6,opt,name=agent_append_public_key,json=agentAppendPublicKey,proto3,oneof"`
}

func (*ApiResponse_AgentCreate) isApiResponse_Payload() {}

func (*ApiResponse_AgentList) isApiResponse_Payload() {}

func (*ApiResponse_AgentGet) isApiResponse_Payload() {}

func (*ApiResponse_AgentAppendPublicKey) isApiResponse_Payload() {}

type AgentCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // agent name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCreateRequest) Reset() {
	*x = AgentCreateRequest{}
	mi := &file_pkg_rpc_v1_sshole_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCreateRequest) ProtoMessage() {}

func (x *AgentCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_sshole_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCreateRequest.ProtoReflect.Descriptor instead.
func (*AgentCreateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_sshole_proto_rawDescGZIP(), []int{2}
}

func (x *AgentCreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AgentCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *Agent                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // hub public key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentCreateResponse) Reset() {
	*x = AgentCreateResponse{}
	mi := &file_pkg_rpc_v1_sshole_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentCreateResponse) ProtoMessage() {}

func (x *AgentCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_sshole_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentCreateResponse.ProtoReflect.Descriptor instead.
func (*AgentCreateResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_sshole_proto_rawDescGZIP(), []int{3}
}

func (x *AgentCreateResponse) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

func (x *AgentCreateResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type AgentListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentListRequest) Reset() {
	*x = AgentListRequest{}
	mi := &file_pkg_rpc_v1_sshole_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentListRequest) ProtoMessage() {}

func (x *AgentListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_sshole_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentListRequest.ProtoReflect.Descriptor instead.
func (*AgentListRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_sshole_proto_rawDescGZIP(), []int{4}
}

type AgentListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         []*Agent               `protobuf:"bytes,1,rep,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentListResponse) Reset() {
	*x = AgentListResponse{}
	mi := &file_pkg_rpc_v1_sshole_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentListResponse) ProtoMessage() {}

func (x *AgentListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_sshole_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentListResponse.ProtoReflect.Descriptor instead.
func (*AgentListResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_sshole_proto_rawDescGZIP(), []int{5}
}

func (x *AgentListResponse) GetAgent() []*Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

type AgentGetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // agent name
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentGetRequest) Reset() {
	*x = AgentGetRequest{}
	mi := &file_pkg_rpc_v1_sshole_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentGetRequest) ProtoMessage() {}

func (x *AgentGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_sshole_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentGetRequest.ProtoReflect.Descriptor instead.
func (*AgentGetRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_sshole_proto_rawDescGZIP(), []int{6}
}

func (x *AgentGetRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AgentGetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agent         *Agent                 `protobuf:"bytes,1,opt,name=agent,proto3" json:"agent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentGetResponse) Reset() {
	*x = AgentGetResponse{}
	mi := &file_pkg_rpc_v1_sshole_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentGetResponse) ProtoMessage() {}

func (x *AgentGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_sshole_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentGetResponse.ProtoReflect.Descriptor instead.
func (*AgentGetResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_sshole_proto_rawDescGZIP(), []int{7}
}

func (x *AgentGetResponse) GetAgent() *Agent {
	if x != nil {
		return x.Agent
	}
	return nil
}

type AgentAppendPublicKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`                            // agent name
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // hub public key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentAppendPublicKeyRequest) Reset() {
	*x = AgentAppendPublicKeyRequest{}
	mi := &file_pkg_rpc_v1_sshole_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentAppendPublicKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentAppendPublicKeyRequest) ProtoMessage() {}

func (x *AgentAppendPublicKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_sshole_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentAppendPublicKeyRequest.ProtoReflect.Descriptor instead.
func (*AgentAppendPublicKeyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_sshole_proto_rawDescGZIP(), []int{8}
}

func (x *AgentAppendPublicKeyRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AgentAppendPublicKeyRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type AgentAppendPublicKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentAppendPublicKeyResponse) Reset() {
	*x = AgentAppendPublicKeyResponse{}
	mi := &file_pkg_rpc_v1_sshole_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentAppendPublicKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentAppendPublicKeyResponse) ProtoMessage() {}

func (x *AgentAppendPublicKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_sshole_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentAppendPublicKeyResponse.ProtoReflect.Descriptor instead.
func (*AgentAppendPublicKeyResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_sshole_proto_rawDescGZIP(), []int{9}
}

type Agent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`  // agent name
	Port          uint32                 `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"` // hub agent port
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Agent) Reset() {
	*x = Agent{}
	mi := &file_pkg_rpc_v1_sshole_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Agent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Agent) ProtoMessage() {}

func (x *Agent) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_sshole_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Agent.ProtoReflect.Descriptor instead.
func (*Agent) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_sshole_proto_rawDescGZIP(), []int{10}
}

func (x *Agent) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Agent) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

var File_pkg_rpc_v1_sshole_proto protoreflect.FileDescriptor

const file_pkg_rpc_v1_sshole_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/rpc/v1/sshole.proto\x12\n" +
	"pkg.rpc.v1\"\xcd\x02\n" +
	"\n" +
	"ApiRequest\x12\x12\n" +
	"\x04auth\x18\x01 \x01(\tR\x04auth\x12C\n" +
	"\fagent_create\x18\x02 \x01(\v2\x1e.pkg.rpc.v1.AgentCreateRequestH\x00R\vagentCreate\x12=\n" +
	"\n" +
	"agent_list\x18\x03 \x01(\v2\x1c.pkg.rpc.v1.AgentListRequestH\x00R\tagentList\x12:\n" +
	"\tagent_get\x18\x04 \x01(\v2\x1b.pkg.rpc.v1.AgentGetRequestH\x00R\bagentGet\x12`\n" +
	"\x17agent_append_public_key\x18\x05 \x01(\v2'.pkg.rpc.v1.AgentAppendPublicKeyRequestH\x00R\x14agentAppendPublicKeyB\t\n" +
	"\apayload\"\xec\x02\n" +
	"\vApiResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12D\n" +
	"\fagent_create\x18\x03 \x01(\v2\x1f.pkg.rpc.v1.AgentCreateResponseH\x00R\vagentCreate\x12>\n" +
	"\n" +
	"agent_list\x18\x04 \x01(\v2\x1d.pkg.rpc.v1.AgentListResponseH\x00R\tagentList\x12;\n" +
	"\tagent_get\x18\x05 \x01(\v2\x1c.pkg.rpc.v1.AgentGetResponseH\x00R\bagentGet\x12a\n" +
	"\x17agent_append_public_key\x18\x06 \x01(\v2(.pkg.rpc.v1.AgentAppendPublicKeyResponseH\x00R\x14agentAppendPublicKeyB\t\n" +
	"\apayload\"(\n" +
	"\x12AgentCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"]\n" +
	"\x13AgentCreateResponse\x12'\n" +
	"\x05agent\x18\x01 \x01(\v2\x11.pkg.rpc.v1.AgentR\x05agent\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\"\x12\n" +
	"\x10AgentListRequest\"<\n" +
	"\x11AgentListResponse\x12'\n" +
	"\x05agent\x18\x01 \x03(\v2\x11.pkg.rpc.v1.AgentR\x05agent\"%\n" +
	"\x0fAgentGetRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\";\n" +
	"\x10AgentGetResponse\x12'\n" +
	"\x05agent\x18\x01 \x01(\v2\x11.pkg.rpc.v1.AgentR\x05agent\"P\n" +
	"\x1bAgentAppendPublicKeyRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\"\x1e\n" +
	"\x1cAgentAppendPublicKeyResponse\"/\n" +
	"\x05Agent\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04port\x18\x02 \x01(\rR\x04port2\x99\x02\n" +
	"\vHoleService\x12@\n" +
	"\vAgentCreate\x12\x16.pkg.rpc.v1.ApiRequest\x1a\x17.pkg.rpc.v1.ApiResponse\"\x00\x12>\n" +
	"\tAgentList\x12\x16.pkg.rpc.v1.ApiRequest\x1a\x17.pkg.rpc.v1.ApiResponse\"\x00\x12=\n" +
	"\bAgentGet\x12\x16.pkg.rpc.v1.ApiRequest\x1a\x17.pkg.rpc.v1.ApiResponse\"\x00\x12I\n" +
	"\x14AgentAppendPublicKey\x12\x16.pkg.rpc.v1.ApiRequest\x1a\x17.pkg.rpc.v1.ApiResponse\"\x00B.Z,github.com/117503445/sshole/pkg/rpc/v1;rpcv1b\x06proto3"

var (
	file_pkg_rpc_v1_sshole_proto_rawDescOnce sync.Once
	file_pkg_rpc_v1_sshole_proto_rawDescData []byte
)

func file_pkg_rpc_v1_sshole_proto_rawDescGZIP() []byte {
	file_pkg_rpc_v1_sshole_proto_rawDescOnce.Do(func() {
		file_pkg_rpc_v1_sshole_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_rpc_v1_sshole_proto_rawDesc), len(file_pkg_rpc_v1_sshole_proto_rawDesc)))
	})
	return file_pkg_rpc_v1_sshole_proto_rawDescData
}

var file_pkg_rpc_v1_sshole_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_pkg_rpc_v1_sshole_proto_goTypes = []any{
	(*ApiRequest)(nil),                   // 0: pkg.rpc.v1.ApiRequest
	(*ApiResponse)(nil),                  // 1: pkg.rpc.v1.ApiResponse
	(*AgentCreateRequest)(nil),           // 2: pkg.rpc.v1.AgentCreateRequest
	(*AgentCreateResponse)(nil),          // 3: pkg.rpc.v1.AgentCreateResponse
	(*AgentListRequest)(nil),             // 4: pkg.rpc.v1.AgentListRequest
	(*AgentListResponse)(nil),            // 5: pkg.rpc.v1.AgentListResponse
	(*AgentGetRequest)(nil),              // 6: pkg.rpc.v1.AgentGetRequest
	(*AgentGetResponse)(nil),             // 7: pkg.rpc.v1.AgentGetResponse
	(*AgentAppendPublicKeyRequest)(nil),  // 8: pkg.rpc.v1.AgentAppendPublicKeyRequest
	(*AgentAppendPublicKeyResponse)(nil), // 9: pkg.rpc.v1.AgentAppendPublicKeyResponse
	(*Agent)(nil),                        // 10: pkg.rpc.v1.Agent
}
var file_pkg_rpc_v1_sshole_proto_depIdxs = []int32{
	2,  // 0: pkg.rpc.v1.ApiRequest.agent_create:type_name -> pkg.rpc.v1.AgentCreateRequest
	4,  // 1: pkg.rpc.v1.ApiRequest.agent_list:type_name -> pkg.rpc.v1.AgentListRequest
	6,  // 2: pkg.rpc.v1.ApiRequest.agent_get:type_name -> pkg.rpc.v1.AgentGetRequest
	8,  // 3: pkg.rpc.v1.ApiRequest.agent_append_public_key:type_name -> pkg.rpc.v1.AgentAppendPublicKeyRequest
	3,  // 4: pkg.rpc.v1.ApiResponse.agent_create:type_name -> pkg.rpc.v1.AgentCreateResponse
	5,  // 5: pkg.rpc.v1.ApiResponse.agent_list:type_name -> pkg.rpc.v1.AgentListResponse
	7,  // 6: pkg.rpc.v1.ApiResponse.agent_get:type_name -> pkg.rpc.v1.AgentGetResponse
	9,  // 7: pkg.rpc.v1.ApiResponse.agent_append_public_key:type_name -> pkg.rpc.v1.AgentAppendPublicKeyResponse
	10, // 8: pkg.rpc.v1.AgentCreateResponse.agent:type_name -> pkg.rpc.v1.Agent
	10, // 9: pkg.rpc.v1.AgentListResponse.agent:type_name -> pkg.rpc.v1.Agent
	10, // 10: pkg.rpc.v1.AgentGetResponse.agent:type_name -> pkg.rpc.v1.Agent
	0,  // 11: pkg.rpc.v1.HoleService.AgentCreate:input_type -> pkg.rpc.v1.ApiRequest
	0,  // 12: pkg.rpc.v1.HoleService.AgentList:input_type -> pkg.rpc.v1.ApiRequest
	0,  // 13: pkg.rpc.v1.HoleService.AgentGet:input_type -> pkg.rpc.v1.ApiRequest
	0,  // 14: pkg.rpc.v1.HoleService.AgentAppendPublicKey:input_type -> pkg.rpc.v1.ApiRequest
	1,  // 15: pkg.rpc.v1.HoleService.AgentCreate:output_type -> pkg.rpc.v1.ApiResponse
	1,  // 16: pkg.rpc.v1.HoleService.AgentList:output_type -> pkg.rpc.v1.ApiResponse
	1,  // 17: pkg.rpc.v1.HoleService.AgentGet:output_type -> pkg.rpc.v1.ApiResponse
	1,  // 18: pkg.rpc.v1.HoleService.AgentAppendPublicKey:output_type -> pkg.rpc.v1.ApiResponse
	15, // [15:19] is the sub-list for method output_type
	11, // [11:15] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_pkg_rpc_v1_sshole_proto_init() }
func file_pkg_rpc_v1_sshole_proto_init() {
	if File_pkg_rpc_v1_sshole_proto != nil {
		return
	}
	file_pkg_rpc_v1_sshole_proto_msgTypes[0].OneofWrappers = []any{
		(*ApiRequest_AgentCreate)(nil),
		(*ApiRequest_AgentList)(nil),
		(*ApiRequest_AgentGet)(nil),
		(*ApiRequest_AgentAppendPublicKey)(nil),
	}
	file_pkg_rpc_v1_sshole_proto_msgTypes[1].OneofWrappers = []any{
		(*ApiResponse_AgentCreate)(nil),
		(*ApiResponse_AgentList)(nil),
		(*ApiResponse_AgentGet)(nil),
		(*ApiResponse_AgentAppendPublicKey)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_rpc_v1_sshole_proto_rawDesc), len(file_pkg_rpc_v1_sshole_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_rpc_v1_sshole_proto_goTypes,
		DependencyIndexes: file_pkg_rpc_v1_sshole_proto_depIdxs,
		MessageInfos:      file_pkg_rpc_v1_sshole_proto_msgTypes,
	}.Build()
	File_pkg_rpc_v1_sshole_proto = out.File
	file_pkg_rpc_v1_sshole_proto_goTypes = nil
	file_pkg_rpc_v1_sshole_proto_depIdxs = nil
}
