// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: pkg/rpc/v1/sshole.proto

package rpcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ListAgentsRequest 请求所有 agent 的固定映射信息。
type ListAgentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsRequest) Reset() {
	*x = ListAgentsRequest{}
	mi := &file_pkg_rpc_v1_sshole_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsRequest) ProtoMessage() {}

func (x *ListAgentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_sshole_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsRequest.ProtoReflect.Descriptor instead.
func (*ListAgentsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_sshole_proto_rawDescGZIP(), []int{0}
}

// AgentInfo 描述一个 agent 的公开信息。
type AgentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentName     string                 `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	HubPort       int32                  `protobuf:"varint,2,opt,name=hub_port,json=hubPort,proto3" json:"hub_port,omitempty"`
	Online        bool                   `protobuf:"varint,3,opt,name=online,proto3" json:"online,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_pkg_rpc_v1_sshole_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_sshole_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_sshole_proto_rawDescGZIP(), []int{1}
}

func (x *AgentInfo) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *AgentInfo) GetHubPort() int32 {
	if x != nil {
		return x.HubPort
	}
	return 0
}

func (x *AgentInfo) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

// ListAgentsResponse 返回 agent 列表。
type ListAgentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Agents        []*AgentInfo           `protobuf:"bytes,1,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAgentsResponse) Reset() {
	*x = ListAgentsResponse{}
	mi := &file_pkg_rpc_v1_sshole_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAgentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAgentsResponse) ProtoMessage() {}

func (x *ListAgentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_sshole_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAgentsResponse.ProtoReflect.Descriptor instead.
func (*ListAgentsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_sshole_proto_rawDescGZIP(), []int{2}
}

func (x *ListAgentsResponse) GetAgents() []*AgentInfo {
	if x != nil {
		return x.Agents
	}
	return nil
}

// AppendKnownHostRequest 将公钥行写入指定 agent 的 known_hosts。
type AppendKnownHostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentName     string                 `protobuf:"bytes,1,opt,name=agent_name,json=agentName,proto3" json:"agent_name,omitempty"`
	PublicKey     string                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendKnownHostRequest) Reset() {
	*x = AppendKnownHostRequest{}
	mi := &file_pkg_rpc_v1_sshole_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendKnownHostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendKnownHostRequest) ProtoMessage() {}

func (x *AppendKnownHostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_sshole_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendKnownHostRequest.ProtoReflect.Descriptor instead.
func (*AppendKnownHostRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_sshole_proto_rawDescGZIP(), []int{3}
}

func (x *AppendKnownHostRequest) GetAgentName() string {
	if x != nil {
		return x.AgentName
	}
	return ""
}

func (x *AppendKnownHostRequest) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

type AppendKnownHostResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendKnownHostResponse) Reset() {
	*x = AppendKnownHostResponse{}
	mi := &file_pkg_rpc_v1_sshole_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendKnownHostResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendKnownHostResponse) ProtoMessage() {}

func (x *AppendKnownHostResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_sshole_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendKnownHostResponse.ProtoReflect.Descriptor instead.
func (*AppendKnownHostResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_sshole_proto_rawDescGZIP(), []int{4}
}

var File_pkg_rpc_v1_sshole_proto protoreflect.FileDescriptor

const file_pkg_rpc_v1_sshole_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/rpc/v1/sshole.proto\x12\n" +
	"pkg.rpc.v1\"\x13\n" +
	"\x11ListAgentsRequest\"]\n" +
	"\tAgentInfo\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x01 \x01(\tR\tagentName\x12\x19\n" +
	"\bhub_port\x18\x02 \x01(\x05R\ahubPort\x12\x16\n" +
	"\x06online\x18\x03 \x01(\bR\x06online\"C\n" +
	"\x12ListAgentsResponse\x12-\n" +
	"\x06agents\x18\x01 \x03(\v2\x15.pkg.rpc.v1.AgentInfoR\x06agents\"V\n" +
	"\x16AppendKnownHostRequest\x12\x1d\n" +
	"\n" +
	"agent_name\x18\x01 \x01(\tR\tagentName\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\tR\tpublicKey\"\x19\n" +
	"\x17AppendKnownHostResponse2\xb6\x01\n" +
	"\vHoleService\x12K\n" +
	"\n" +
	"ListAgents\x12\x1d.pkg.rpc.v1.ListAgentsRequest\x1a\x1e.pkg.rpc.v1.ListAgentsResponse\x12Z\n" +
	"\x0fAppendKnownHost\x12\".pkg.rpc.v1.AppendKnownHostRequest\x1a#.pkg.rpc.v1.AppendKnownHostResponseB.Z,github.com/117503445/sshole/pkg/rpc/v1;rpcv1b\x06proto3"

var (
	file_pkg_rpc_v1_sshole_proto_rawDescOnce sync.Once
	file_pkg_rpc_v1_sshole_proto_rawDescData []byte
)

func file_pkg_rpc_v1_sshole_proto_rawDescGZIP() []byte {
	file_pkg_rpc_v1_sshole_proto_rawDescOnce.Do(func() {
		file_pkg_rpc_v1_sshole_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_rpc_v1_sshole_proto_rawDesc), len(file_pkg_rpc_v1_sshole_proto_rawDesc)))
	})
	return file_pkg_rpc_v1_sshole_proto_rawDescData
}

var file_pkg_rpc_v1_sshole_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_pkg_rpc_v1_sshole_proto_goTypes = []any{
	(*ListAgentsRequest)(nil),       // 0: pkg.rpc.v1.ListAgentsRequest
	(*AgentInfo)(nil),               // 1: pkg.rpc.v1.AgentInfo
	(*ListAgentsResponse)(nil),      // 2: pkg.rpc.v1.ListAgentsResponse
	(*AppendKnownHostRequest)(nil),  // 3: pkg.rpc.v1.AppendKnownHostRequest
	(*AppendKnownHostResponse)(nil), // 4: pkg.rpc.v1.AppendKnownHostResponse
}
var file_pkg_rpc_v1_sshole_proto_depIdxs = []int32{
	1, // 0: pkg.rpc.v1.ListAgentsResponse.agents:type_name -> pkg.rpc.v1.AgentInfo
	0, // 1: pkg.rpc.v1.HoleService.ListAgents:input_type -> pkg.rpc.v1.ListAgentsRequest
	3, // 2: pkg.rpc.v1.HoleService.AppendKnownHost:input_type -> pkg.rpc.v1.AppendKnownHostRequest
	2, // 3: pkg.rpc.v1.HoleService.ListAgents:output_type -> pkg.rpc.v1.ListAgentsResponse
	4, // 4: pkg.rpc.v1.HoleService.AppendKnownHost:output_type -> pkg.rpc.v1.AppendKnownHostResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_pkg_rpc_v1_sshole_proto_init() }
func file_pkg_rpc_v1_sshole_proto_init() {
	if File_pkg_rpc_v1_sshole_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_rpc_v1_sshole_proto_rawDesc), len(file_pkg_rpc_v1_sshole_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_rpc_v1_sshole_proto_goTypes,
		DependencyIndexes: file_pkg_rpc_v1_sshole_proto_depIdxs,
		MessageInfos:      file_pkg_rpc_v1_sshole_proto_msgTypes,
	}.Build()
	File_pkg_rpc_v1_sshole_proto = out.File
	file_pkg_rpc_v1_sshole_proto_goTypes = nil
	file_pkg_rpc_v1_sshole_proto_depIdxs = nil
}
