// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: pkg/rpc/v1/sshole.proto

package rpcv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AcquireConnectionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireConnectionRequest) Reset() {
	*x = AcquireConnectionRequest{}
	mi := &file_pkg_rpc_v1_sshole_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireConnectionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireConnectionRequest) ProtoMessage() {}

func (x *AcquireConnectionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_sshole_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireConnectionRequest.ProtoReflect.Descriptor instead.
func (*AcquireConnectionRequest) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_sshole_proto_rawDescGZIP(), []int{0}
}

func (x *AcquireConnectionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AcquireConnectionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Auth          string                 `protobuf:"bytes,2,opt,name=auth,proto3" json:"auth,omitempty"`
	Port          int32                  `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	SshPublicKey  string                 `protobuf:"bytes,4,opt,name=ssh_public_key,json=sshPublicKey,proto3" json:"ssh_public_key,omitempty"`
	SshPrivateKey string                 `protobuf:"bytes,5,opt,name=ssh_private_key,json=sshPrivateKey,proto3" json:"ssh_private_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcquireConnectionResponse) Reset() {
	*x = AcquireConnectionResponse{}
	mi := &file_pkg_rpc_v1_sshole_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcquireConnectionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcquireConnectionResponse) ProtoMessage() {}

func (x *AcquireConnectionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_rpc_v1_sshole_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcquireConnectionResponse.ProtoReflect.Descriptor instead.
func (*AcquireConnectionResponse) Descriptor() ([]byte, []int) {
	return file_pkg_rpc_v1_sshole_proto_rawDescGZIP(), []int{1}
}

func (x *AcquireConnectionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AcquireConnectionResponse) GetAuth() string {
	if x != nil {
		return x.Auth
	}
	return ""
}

func (x *AcquireConnectionResponse) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *AcquireConnectionResponse) GetSshPublicKey() string {
	if x != nil {
		return x.SshPublicKey
	}
	return ""
}

func (x *AcquireConnectionResponse) GetSshPrivateKey() string {
	if x != nil {
		return x.SshPrivateKey
	}
	return ""
}

var File_pkg_rpc_v1_sshole_proto protoreflect.FileDescriptor

const file_pkg_rpc_v1_sshole_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/rpc/v1/sshole.proto\x12\n" +
	"pkg.rpc.v1\"*\n" +
	"\x18AcquireConnectionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xab\x01\n" +
	"\x19AcquireConnectionResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04auth\x18\x02 \x01(\tR\x04auth\x12\x12\n" +
	"\x04port\x18\x03 \x01(\x05R\x04port\x12$\n" +
	"\x0essh_public_key\x18\x04 \x01(\tR\fsshPublicKey\x12&\n" +
	"\x0fssh_private_key\x18\x05 \x01(\tR\rsshPrivateKey2q\n" +
	"\vHoleService\x12b\n" +
	"\x11AcquireConnection\x12$.pkg.rpc.v1.AcquireConnectionRequest\x1a%.pkg.rpc.v1.AcquireConnectionResponse\"\x00B\x19Z\x17sshole/pkg/rpc/v1;rpcv1b\x06proto3"

var (
	file_pkg_rpc_v1_sshole_proto_rawDescOnce sync.Once
	file_pkg_rpc_v1_sshole_proto_rawDescData []byte
)

func file_pkg_rpc_v1_sshole_proto_rawDescGZIP() []byte {
	file_pkg_rpc_v1_sshole_proto_rawDescOnce.Do(func() {
		file_pkg_rpc_v1_sshole_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_rpc_v1_sshole_proto_rawDesc), len(file_pkg_rpc_v1_sshole_proto_rawDesc)))
	})
	return file_pkg_rpc_v1_sshole_proto_rawDescData
}

var file_pkg_rpc_v1_sshole_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_rpc_v1_sshole_proto_goTypes = []any{
	(*AcquireConnectionRequest)(nil),  // 0: pkg.rpc.v1.AcquireConnectionRequest
	(*AcquireConnectionResponse)(nil), // 1: pkg.rpc.v1.AcquireConnectionResponse
}
var file_pkg_rpc_v1_sshole_proto_depIdxs = []int32{
	0, // 0: pkg.rpc.v1.HoleService.AcquireConnection:input_type -> pkg.rpc.v1.AcquireConnectionRequest
	1, // 1: pkg.rpc.v1.HoleService.AcquireConnection:output_type -> pkg.rpc.v1.AcquireConnectionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_rpc_v1_sshole_proto_init() }
func file_pkg_rpc_v1_sshole_proto_init() {
	if File_pkg_rpc_v1_sshole_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_rpc_v1_sshole_proto_rawDesc), len(file_pkg_rpc_v1_sshole_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_rpc_v1_sshole_proto_goTypes,
		DependencyIndexes: file_pkg_rpc_v1_sshole_proto_depIdxs,
		MessageInfos:      file_pkg_rpc_v1_sshole_proto_msgTypes,
	}.Build()
	File_pkg_rpc_v1_sshole_proto = out.File
	file_pkg_rpc_v1_sshole_proto_goTypes = nil
	file_pkg_rpc_v1_sshole_proto_depIdxs = nil
}
