version: 3

tasks:
  clear:
    desc: "清屏"
    internal: true
    silent: true
    run: once
    cmds:
      - clear || true

  default:
    desc: "默认任务"
    deps: ["clear"]
    cmds:
      - task: dev

  dev:
    desc: "开发模式"
    cmds:
      - task: ":test:e2e"
