version: 3

tasks:
  gen:
    desc: "生成 RPC 代码"
    deps: [":base:clear"]
    sources:
      - pkg/rpc/v1/sshole.proto
      - buf.gen.yaml
      - buf.yaml
    generates:
      - ./pkg/rpc/v1/sshole.pb.go
      - ./pkg/rpc/v1/rpcv1connect/sshole.connect.go
    cmds:
      - buf generate
