// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: pkg/rpc/v1/sshole.proto

package rpcv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/117503445/sshole/pkg/rpc/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// HoleServiceName is the fully-qualified name of the HoleService service.
	HoleServiceName = "pkg.rpc.v1.HoleService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// HoleServiceListAgentsProcedure is the fully-qualified name of the HoleService's ListAgents RPC.
	HoleServiceListAgentsProcedure = "/pkg.rpc.v1.HoleService/ListAgents"
	// HoleServiceAppendKnownHostProcedure is the fully-qualified name of the HoleService's
	// AppendKnownHost RPC.
	HoleServiceAppendKnownHostProcedure = "/pkg.rpc.v1.HoleService/AppendKnownHost"
)

// HoleServiceClient is a client for the pkg.rpc.v1.HoleService service.
type HoleServiceClient interface {
	// ListAgents 返回所有已配置 agent 的映射与在线状态。
	ListAgents(context.Context, *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error)
	// AppendKnownHost 让 Hub 通知 Agent 将提供的公钥行追加到 known_hosts。
	AppendKnownHost(context.Context, *connect.Request[v1.AppendKnownHostRequest]) (*connect.Response[v1.AppendKnownHostResponse], error)
}

// NewHoleServiceClient constructs a client for the pkg.rpc.v1.HoleService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewHoleServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) HoleServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	holeServiceMethods := v1.File_pkg_rpc_v1_sshole_proto.Services().ByName("HoleService").Methods()
	return &holeServiceClient{
		listAgents: connect.NewClient[v1.ListAgentsRequest, v1.ListAgentsResponse](
			httpClient,
			baseURL+HoleServiceListAgentsProcedure,
			connect.WithSchema(holeServiceMethods.ByName("ListAgents")),
			connect.WithClientOptions(opts...),
		),
		appendKnownHost: connect.NewClient[v1.AppendKnownHostRequest, v1.AppendKnownHostResponse](
			httpClient,
			baseURL+HoleServiceAppendKnownHostProcedure,
			connect.WithSchema(holeServiceMethods.ByName("AppendKnownHost")),
			connect.WithClientOptions(opts...),
		),
	}
}

// holeServiceClient implements HoleServiceClient.
type holeServiceClient struct {
	listAgents      *connect.Client[v1.ListAgentsRequest, v1.ListAgentsResponse]
	appendKnownHost *connect.Client[v1.AppendKnownHostRequest, v1.AppendKnownHostResponse]
}

// ListAgents calls pkg.rpc.v1.HoleService.ListAgents.
func (c *holeServiceClient) ListAgents(ctx context.Context, req *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error) {
	return c.listAgents.CallUnary(ctx, req)
}

// AppendKnownHost calls pkg.rpc.v1.HoleService.AppendKnownHost.
func (c *holeServiceClient) AppendKnownHost(ctx context.Context, req *connect.Request[v1.AppendKnownHostRequest]) (*connect.Response[v1.AppendKnownHostResponse], error) {
	return c.appendKnownHost.CallUnary(ctx, req)
}

// HoleServiceHandler is an implementation of the pkg.rpc.v1.HoleService service.
type HoleServiceHandler interface {
	// ListAgents 返回所有已配置 agent 的映射与在线状态。
	ListAgents(context.Context, *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error)
	// AppendKnownHost 让 Hub 通知 Agent 将提供的公钥行追加到 known_hosts。
	AppendKnownHost(context.Context, *connect.Request[v1.AppendKnownHostRequest]) (*connect.Response[v1.AppendKnownHostResponse], error)
}

// NewHoleServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewHoleServiceHandler(svc HoleServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	holeServiceMethods := v1.File_pkg_rpc_v1_sshole_proto.Services().ByName("HoleService").Methods()
	holeServiceListAgentsHandler := connect.NewUnaryHandler(
		HoleServiceListAgentsProcedure,
		svc.ListAgents,
		connect.WithSchema(holeServiceMethods.ByName("ListAgents")),
		connect.WithHandlerOptions(opts...),
	)
	holeServiceAppendKnownHostHandler := connect.NewUnaryHandler(
		HoleServiceAppendKnownHostProcedure,
		svc.AppendKnownHost,
		connect.WithSchema(holeServiceMethods.ByName("AppendKnownHost")),
		connect.WithHandlerOptions(opts...),
	)
	return "/pkg.rpc.v1.HoleService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case HoleServiceListAgentsProcedure:
			holeServiceListAgentsHandler.ServeHTTP(w, r)
		case HoleServiceAppendKnownHostProcedure:
			holeServiceAppendKnownHostHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedHoleServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedHoleServiceHandler struct{}

func (UnimplementedHoleServiceHandler) ListAgents(context.Context, *connect.Request[v1.ListAgentsRequest]) (*connect.Response[v1.ListAgentsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pkg.rpc.v1.HoleService.ListAgents is not implemented"))
}

func (UnimplementedHoleServiceHandler) AppendKnownHost(context.Context, *connect.Request[v1.AppendKnownHostRequest]) (*connect.Response[v1.AppendKnownHostResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pkg.rpc.v1.HoleService.AppendKnownHost is not implemented"))
}
