// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: pkg/rpc/v1/sshole.proto

package rpcv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	v1 "sshole/pkg/rpc/v1"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// HoleServiceName is the fully-qualified name of the HoleService service.
	HoleServiceName = "pkg.rpc.v1.HoleService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// HoleServiceAcquireConnectionProcedure is the fully-qualified name of the HoleService's
	// AcquireConnection RPC.
	HoleServiceAcquireConnectionProcedure = "/pkg.rpc.v1.HoleService/AcquireConnection"
)

// HoleServiceClient is a client for the pkg.rpc.v1.HoleService service.
type HoleServiceClient interface {
	AcquireConnection(context.Context, *connect.Request[v1.AcquireConnectionRequest]) (*connect.Response[v1.AcquireConnectionResponse], error)
}

// NewHoleServiceClient constructs a client for the pkg.rpc.v1.HoleService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewHoleServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) HoleServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	holeServiceMethods := v1.File_pkg_rpc_v1_sshole_proto.Services().ByName("HoleService").Methods()
	return &holeServiceClient{
		acquireConnection: connect.NewClient[v1.AcquireConnectionRequest, v1.AcquireConnectionResponse](
			httpClient,
			baseURL+HoleServiceAcquireConnectionProcedure,
			connect.WithSchema(holeServiceMethods.ByName("AcquireConnection")),
			connect.WithClientOptions(opts...),
		),
	}
}

// holeServiceClient implements HoleServiceClient.
type holeServiceClient struct {
	acquireConnection *connect.Client[v1.AcquireConnectionRequest, v1.AcquireConnectionResponse]
}

// AcquireConnection calls pkg.rpc.v1.HoleService.AcquireConnection.
func (c *holeServiceClient) AcquireConnection(ctx context.Context, req *connect.Request[v1.AcquireConnectionRequest]) (*connect.Response[v1.AcquireConnectionResponse], error) {
	return c.acquireConnection.CallUnary(ctx, req)
}

// HoleServiceHandler is an implementation of the pkg.rpc.v1.HoleService service.
type HoleServiceHandler interface {
	AcquireConnection(context.Context, *connect.Request[v1.AcquireConnectionRequest]) (*connect.Response[v1.AcquireConnectionResponse], error)
}

// NewHoleServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewHoleServiceHandler(svc HoleServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	holeServiceMethods := v1.File_pkg_rpc_v1_sshole_proto.Services().ByName("HoleService").Methods()
	holeServiceAcquireConnectionHandler := connect.NewUnaryHandler(
		HoleServiceAcquireConnectionProcedure,
		svc.AcquireConnection,
		connect.WithSchema(holeServiceMethods.ByName("AcquireConnection")),
		connect.WithHandlerOptions(opts...),
	)
	return "/pkg.rpc.v1.HoleService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case HoleServiceAcquireConnectionProcedure:
			holeServiceAcquireConnectionHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedHoleServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedHoleServiceHandler struct{}

func (UnimplementedHoleServiceHandler) AcquireConnection(context.Context, *connect.Request[v1.AcquireConnectionRequest]) (*connect.Response[v1.AcquireConnectionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pkg.rpc.v1.HoleService.AcquireConnection is not implemented"))
}
