// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: pkg/rpc/v1/sshole.proto

package rpcv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	http "net/http"
	v1 "sshole/pkg/rpc/v1"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// HoleServiceName is the fully-qualified name of the HoleService service.
	HoleServiceName = "pkg.rpc.v1.HoleService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// HoleServiceAgentCreateProcedure is the fully-qualified name of the HoleService's AgentCreate RPC.
	HoleServiceAgentCreateProcedure = "/pkg.rpc.v1.HoleService/AgentCreate"
	// HoleServiceAgentListProcedure is the fully-qualified name of the HoleService's AgentList RPC.
	HoleServiceAgentListProcedure = "/pkg.rpc.v1.HoleService/AgentList"
	// HoleServiceAgentGetProcedure is the fully-qualified name of the HoleService's AgentGet RPC.
	HoleServiceAgentGetProcedure = "/pkg.rpc.v1.HoleService/AgentGet"
	// HoleServiceAgentAppendPublicKeyProcedure is the fully-qualified name of the HoleService's
	// AgentAppendPublicKey RPC.
	HoleServiceAgentAppendPublicKeyProcedure = "/pkg.rpc.v1.HoleService/AgentAppendPublicKey"
)

// HoleServiceClient is a client for the pkg.rpc.v1.HoleService service.
type HoleServiceClient interface {
	// AgentCreate 注册 agent 到 hub
	// hub 分配一个 port 给 agent，并返回 public key
	AgentCreate(context.Context, *connect.Request[v1.ApiRequest]) (*connect.Response[v1.ApiResponse], error)
	// AgentList 获取 agent 列表
	AgentList(context.Context, *connect.Request[v1.ApiRequest]) (*connect.Response[v1.ApiResponse], error)
	// AgentGet 获取 agent 信息
	AgentGet(context.Context, *connect.Request[v1.ApiRequest]) (*connect.Response[v1.ApiResponse], error)
	// AgentAppendPublicKey 追加 public key 到 agent
	AgentAppendPublicKey(context.Context, *connect.Request[v1.ApiRequest]) (*connect.Response[v1.ApiResponse], error)
}

// NewHoleServiceClient constructs a client for the pkg.rpc.v1.HoleService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewHoleServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) HoleServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	holeServiceMethods := v1.File_pkg_rpc_v1_sshole_proto.Services().ByName("HoleService").Methods()
	return &holeServiceClient{
		agentCreate: connect.NewClient[v1.ApiRequest, v1.ApiResponse](
			httpClient,
			baseURL+HoleServiceAgentCreateProcedure,
			connect.WithSchema(holeServiceMethods.ByName("AgentCreate")),
			connect.WithClientOptions(opts...),
		),
		agentList: connect.NewClient[v1.ApiRequest, v1.ApiResponse](
			httpClient,
			baseURL+HoleServiceAgentListProcedure,
			connect.WithSchema(holeServiceMethods.ByName("AgentList")),
			connect.WithClientOptions(opts...),
		),
		agentGet: connect.NewClient[v1.ApiRequest, v1.ApiResponse](
			httpClient,
			baseURL+HoleServiceAgentGetProcedure,
			connect.WithSchema(holeServiceMethods.ByName("AgentGet")),
			connect.WithClientOptions(opts...),
		),
		agentAppendPublicKey: connect.NewClient[v1.ApiRequest, v1.ApiResponse](
			httpClient,
			baseURL+HoleServiceAgentAppendPublicKeyProcedure,
			connect.WithSchema(holeServiceMethods.ByName("AgentAppendPublicKey")),
			connect.WithClientOptions(opts...),
		),
	}
}

// holeServiceClient implements HoleServiceClient.
type holeServiceClient struct {
	agentCreate          *connect.Client[v1.ApiRequest, v1.ApiResponse]
	agentList            *connect.Client[v1.ApiRequest, v1.ApiResponse]
	agentGet             *connect.Client[v1.ApiRequest, v1.ApiResponse]
	agentAppendPublicKey *connect.Client[v1.ApiRequest, v1.ApiResponse]
}

// AgentCreate calls pkg.rpc.v1.HoleService.AgentCreate.
func (c *holeServiceClient) AgentCreate(ctx context.Context, req *connect.Request[v1.ApiRequest]) (*connect.Response[v1.ApiResponse], error) {
	return c.agentCreate.CallUnary(ctx, req)
}

// AgentList calls pkg.rpc.v1.HoleService.AgentList.
func (c *holeServiceClient) AgentList(ctx context.Context, req *connect.Request[v1.ApiRequest]) (*connect.Response[v1.ApiResponse], error) {
	return c.agentList.CallUnary(ctx, req)
}

// AgentGet calls pkg.rpc.v1.HoleService.AgentGet.
func (c *holeServiceClient) AgentGet(ctx context.Context, req *connect.Request[v1.ApiRequest]) (*connect.Response[v1.ApiResponse], error) {
	return c.agentGet.CallUnary(ctx, req)
}

// AgentAppendPublicKey calls pkg.rpc.v1.HoleService.AgentAppendPublicKey.
func (c *holeServiceClient) AgentAppendPublicKey(ctx context.Context, req *connect.Request[v1.ApiRequest]) (*connect.Response[v1.ApiResponse], error) {
	return c.agentAppendPublicKey.CallUnary(ctx, req)
}

// HoleServiceHandler is an implementation of the pkg.rpc.v1.HoleService service.
type HoleServiceHandler interface {
	// AgentCreate 注册 agent 到 hub
	// hub 分配一个 port 给 agent，并返回 public key
	AgentCreate(context.Context, *connect.Request[v1.ApiRequest]) (*connect.Response[v1.ApiResponse], error)
	// AgentList 获取 agent 列表
	AgentList(context.Context, *connect.Request[v1.ApiRequest]) (*connect.Response[v1.ApiResponse], error)
	// AgentGet 获取 agent 信息
	AgentGet(context.Context, *connect.Request[v1.ApiRequest]) (*connect.Response[v1.ApiResponse], error)
	// AgentAppendPublicKey 追加 public key 到 agent
	AgentAppendPublicKey(context.Context, *connect.Request[v1.ApiRequest]) (*connect.Response[v1.ApiResponse], error)
}

// NewHoleServiceHandler builds an HTTP handler from the service implementation. It returns the path
// on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewHoleServiceHandler(svc HoleServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	holeServiceMethods := v1.File_pkg_rpc_v1_sshole_proto.Services().ByName("HoleService").Methods()
	holeServiceAgentCreateHandler := connect.NewUnaryHandler(
		HoleServiceAgentCreateProcedure,
		svc.AgentCreate,
		connect.WithSchema(holeServiceMethods.ByName("AgentCreate")),
		connect.WithHandlerOptions(opts...),
	)
	holeServiceAgentListHandler := connect.NewUnaryHandler(
		HoleServiceAgentListProcedure,
		svc.AgentList,
		connect.WithSchema(holeServiceMethods.ByName("AgentList")),
		connect.WithHandlerOptions(opts...),
	)
	holeServiceAgentGetHandler := connect.NewUnaryHandler(
		HoleServiceAgentGetProcedure,
		svc.AgentGet,
		connect.WithSchema(holeServiceMethods.ByName("AgentGet")),
		connect.WithHandlerOptions(opts...),
	)
	holeServiceAgentAppendPublicKeyHandler := connect.NewUnaryHandler(
		HoleServiceAgentAppendPublicKeyProcedure,
		svc.AgentAppendPublicKey,
		connect.WithSchema(holeServiceMethods.ByName("AgentAppendPublicKey")),
		connect.WithHandlerOptions(opts...),
	)
	return "/pkg.rpc.v1.HoleService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case HoleServiceAgentCreateProcedure:
			holeServiceAgentCreateHandler.ServeHTTP(w, r)
		case HoleServiceAgentListProcedure:
			holeServiceAgentListHandler.ServeHTTP(w, r)
		case HoleServiceAgentGetProcedure:
			holeServiceAgentGetHandler.ServeHTTP(w, r)
		case HoleServiceAgentAppendPublicKeyProcedure:
			holeServiceAgentAppendPublicKeyHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedHoleServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedHoleServiceHandler struct{}

func (UnimplementedHoleServiceHandler) AgentCreate(context.Context, *connect.Request[v1.ApiRequest]) (*connect.Response[v1.ApiResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pkg.rpc.v1.HoleService.AgentCreate is not implemented"))
}

func (UnimplementedHoleServiceHandler) AgentList(context.Context, *connect.Request[v1.ApiRequest]) (*connect.Response[v1.ApiResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pkg.rpc.v1.HoleService.AgentList is not implemented"))
}

func (UnimplementedHoleServiceHandler) AgentGet(context.Context, *connect.Request[v1.ApiRequest]) (*connect.Response[v1.ApiResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pkg.rpc.v1.HoleService.AgentGet is not implemented"))
}

func (UnimplementedHoleServiceHandler) AgentAppendPublicKey(context.Context, *connect.Request[v1.ApiRequest]) (*connect.Response[v1.ApiResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("pkg.rpc.v1.HoleService.AgentAppendPublicKey is not implemented"))
}
